### ISSUE TITLE
Service Request and Action Goal Message Creation Fails for Message Types with Embedded Arrays 

### ISSUE THREAD

**Issue by sgstreet** [ros-teleop/teleop_tools#22]
The function joy_teleop.fill_msg(self, msg, values) does not correctly build ROS message types of the form:

```
string name
geometry_msgs/Pose2D[] poses
```
from the the provided yaml excerpt:

```
  action_goal:
        name: odom
        poses:
          -   x: 2.0
              y: 0.0
              theta: 0.0
          -   x: 2.0
              y: -2.0
              theta: 0
          -  x: 0.0
              y: -2.0
              theta: 0
```
The code should instead use the function genpy.message.fill_message_args which will correctly load the above yaml to the message.

**Comment by bmagyar** [comment]
Hi Stephen,

Could you please elaborate on this? How exactly is it different and why
only for this type, not for others? Do you have an example?

**Comment by sgstreet** [comment]
The fill_msg function does not handle lists correctly.  Attaching:

The action:

```
Plan mission
---
duration time_elapsed
---
string goal_name
```
The Plan message:

```
string frame
Waypoint[] waypoints
```
The Waypoint message:

```
string name
geometry_msgs/Pose2D goal
```
The config yaml:

```
  mission:
    type: action
    action_name: mission/plan
    action_goal:
      mission:
        frame: odom
        waypoints:
          - name: wp11
            goal:
              x: 2.0
              y: 0.0
              theta: 0.0
          - name: wp12
            goal:
              x: 2.0
              y: -2.0
              theta: 0
          - name: wp13
            goal:
              x: 0.0
              y: -2.0
              theta: 0
          - name: wp14
            goal:
              x: 0.0
              y: 0.0
              theta: 0.0
    buttons: [0]
```
This set fails during serialization for the goal because the message was incorrectly built.  I you want a traceback, let me know.....
