### ISSUE TITLE
Deadman not sending stop command (joy)

### ISSUE THREAD

**Issue by glmnet** [ros-teleop/teleop_tools#45]
I might be doing something wrong, even looking at the source code I can't figure out how to get it to work like I want:

I press button, hold down, then move the robot around with joy axes, then stop axes, robot stops release button -> all is ok.
But if I'm moving the robot with the axes, then release the button, the robot keeps moving for a while until I believe my engine controller stops moving because it stops receiving cmd_vel commands, i.e. it never receives a cmd_vel with target velocity of 0.

I was using joy_teleop before and it worked this way, the cmd_vel 0 was sent on button release.

Now this teleop tools seems more flexible and useful for me.

In any case I can send a PR to support this if it will be welcomed.

Relevant config is just this:

````yaml
teleop:
  joy_move:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    deadman_buttons: [4]
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 0.7
      -
        axis: 0
        target: angular.z
        scale: 0.5
````

**Comment by glmnet** [comment]
I've sent a PR for this https://github.com/ros-teleop/teleop_tools/pull/47

**Comment by cosmicog** [comment]
Same thing happened to me while testing `deadman_buttons` option. When I raised my finger up from the configured button while still pushing the speed control stick, I expected my robot to stop moving but it continued executing the last command.

IDK if this is the desired behaviour for deadman switch activity but in my local fork, I fixed it like this:
I introduced a parameter defaulting to `False` to not hurt other people's robots' default behaviour:
```yaml
/**/joy_teleop:
  ros__parameters:
    move:
      type: topic
      interface_type: geometry_msgs/msg/TwistStamped
      topic_name: input_joy/cmd_vel # will publish messages to this
      deadman_buttons: [3] # hold the Y button of F710 to control robot, for safety
      deadman_zeroing_enable: True # <--------- HERE
...
```
```py
class JoyTeleopTopicCommand(JoyTeleopCommand):
    def __init__(...)
...
        # A parameter for resetting velocity commands to 0
        if 'deadman_zeroing_enable' in config:
            self.deadman_zeroing_enable = config['deadman_zeroing_enable']
        else:
            self.deadman_zeroing_enable = False # no need for e.g. position commands
...
```
Then, I changed the beginning of the `run(...)` method (to):
```py
        last_active = self.active
        self.update_active_from_buttons_and_axes(joy_state)
        if self.msg_value is not None and last_active == self.active:
            return
        else:
            msg = self.topic_type()
            if ((isinstance(msg, TwistStamped)) and
                (last_active != self.active) and
                self.deadman_zeroing_enable):
                node.get_logger().debug('Deadman switch activity, zeroing twist command once...')
                msg.header.stamp = node.get_clock().now().to_msg()
                self.pub.publish(msg)
...
```
the original part was looking like this (from):
```py
        last_active = self.active
        self.update_active_from_buttons_and_axes(joy_state)
        if not self.active:
            return
        if self.msg_value is not None and last_active == self.active:
            return
...
```
I tested it and it works as (I) desired.

I even tried removing the joystick's USB & removing its battery 🔋 while driving the robot, and the movement stopped after both.

This may not be the default desired behaviour of this "deadman" feature but I had problems with robots losing wireless connection and keep moving in the past, due to a low joystick battery or wireless interference in a public environment.

@bmagyar Could you help us understand? 🙃 

I can send a PR right away if I didn't misunderstand this parameter.
